engine.physics.fixedTimestep: 0.016666668
engine.physics.gravity:
  - 0
  - -9.81
  - 0
engine.physics.maxBodies: 10240
engine.physics.maxBodyPairs: 65536
engine.physics.maxContactConstraints: 10240
engine.physics.positionSolverIterations: 2
engine.physics.velocitySolverIterations: 10
engine.physics.layerName.0: Default
engine.physics.layerName.1: Static
engine.physics.layerName.2: Player
engine.physics.layerName.3: Enemy
engine.physics.layerName.4: Environment
engine.physics.layerName.5: Trigger
engine.physics.layerName.6: Projectile
engine.physics.layerName.7: Interactable
engine.physics.layerName.8: Layer 8
engine.physics.layerName.9: Layer 9
engine.physics.layerName.10: Layer 10
engine.physics.layerName.11: Layer 11
engine.physics.layerName.12: Layer 12
engine.physics.layerName.13: Layer 13
engine.physics.layerName.14: Layer 14
engine.physics.layerName.15: Layer 15
engine.physics.layerName.16: Layer 16
engine.physics.layerName.17: Layer 17
engine.physics.layerName.18: Layer 18
engine.physics.layerName.19: Layer 19
engine.physics.layerName.20: Layer 20
engine.physics.layerName.21: Layer 21
engine.physics.layerName.22: Layer 22
engine.physics.layerName.23: Layer 23
engine.physics.layerName.24: Layer 24
engine.physics.layerName.25: Layer 25
engine.physics.layerName.26: Layer 26
engine.physics.layerName.27: Layer 27
engine.physics.layerName.28: Layer 28
engine.physics.layerName.29: Layer 29
engine.physics.layerName.30: Layer 30
engine.physics.layerName.31: Layer 31