//
// Text templates for the files scaffolded into a newly-created project, so a
// fresh project is a standalone find_package(Seraph) build with a working
// starter script. Kept out of ProjectManager.cpp to keep that file readable.
//

#pragma once

#include <cstddef>
#include <string>

namespace Seraph::ProjectTemplates
{

namespace detail
{
    inline std::string Replace(
        std::string s, const std::string& from, const std::string& to)
    {
        for (std::size_t p = s.find(from); p != std::string::npos;
             p = s.find(from, p + to.size()))
            s.replace(p, from.size(), to);
        return s;
    }
} // namespace detail

// Standalone CMakeLists for a project's Game module. It find_package(Seraph)s a
// locally-built engine (path supplied by CMakePresets.json / -DSeraph_DIR) and
// builds libGame — a SHARED module the editor/runtime load at runtime.
inline std::string GameCMakeLists(const std::string& projectName)
{
    const std::string tpl = R"cmake(cmake_minimum_required(VERSION 3.30)
project(@NAME@ CXX)
set(CMAKE_CXX_STANDARD 20)

# The Seraph engine you built. CMakePresets.json passes -DSeraph_DIR; or set it
# yourself: -DSeraph_DIR=<engine-build-dir> (where SeraphConfig.cmake lives).
find_package(Seraph REQUIRED)

file(GLOB_RECURSE GAME_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.h")

# libGame: this project's native C++ gameplay scripts. Loaded at runtime by the
# editor/runtime via SDL_LoadObject (NOT linked into them); its SP_REGISTER_SCRIPT
# initializers register into libSeraph's ScriptRegistry on load.
add_library(Game SHARED ${GAME_SOURCES})
target_link_libraries(Game PRIVATE Seraph::Seraph)

# rpath: the engine bin (dev-time load) + @loader_path/.. (so a PACKAGED libGame,
# which sits in <game>/cache/, finds libSeraph one dir up next to the exe).
if (APPLE)
    set(GAME_RPATH "@loader_path/..;@loader_path;${SERAPH_ENGINE_BUILD_DIR}/bin")
elseif (UNIX)
    set(GAME_RPATH "$ORIGIN/..;$ORIGIN;${SERAPH_ENGINE_BUILD_DIR}/bin")
endif ()
set_target_properties(Game PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/cache"
    BUILD_RPATH   "${GAME_RPATH}"
    INSTALL_RPATH "${GAME_RPATH}"
    DEBUG_POSTFIX "")

# IDE run targets (the green "Run" arrow):
#   RunEditor   — open this project in the Seraph editor
#   PackageGame — build a runnable, distributable game folder
#
# These are real executables, not custom targets, so the IDE "Run" button can
# launch them: a custom target has no executable artifact, so Run does nothing
# and only Build/hammer fires its command. Each launcher just exec()s the
# prebuilt editor. The sources are (re)generated on every configure so the
# baked-in editor path stays current, and land in the build tree (never the
# source tree). EXCLUDE_FROM_ALL keeps them out of a plain "build all".
set(SERAPH_SPROJ "${CMAKE_CURRENT_SOURCE_DIR}/@NAME@.sproj")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/launch/RunEditor.cpp"
"// Generated by CMake — launches the Seraph editor. Do not edit.
#if defined(_WIN32)
#  include <process.h>
#else
#  include <unistd.h>
#endif
int main()
{
    const char* argv[] = { \"${SERAPH_EDITOR_EXECUTABLE}\", \"--project\", \"${SERAPH_SPROJ}\", 0 };
#if defined(_WIN32)
    return (int) _spawnv(_P_WAIT, argv[0], (const char* const*) argv);
#else
    execv(argv[0], (char* const*) argv);
    return 127; // exec only returns on failure
#endif
}
")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/launch/PackageGame.cpp"
"// Generated by CMake — packages the game via the Seraph editor. Do not edit.
#if defined(_WIN32)
#  include <process.h>
#else
#  include <unistd.h>
#endif
int main()
{
    const char* argv[] = { \"${SERAPH_EDITOR_EXECUTABLE}\", \"--package\", \"${SERAPH_SPROJ}\", 0 };
#if defined(_WIN32)
    return (int) _spawnv(_P_WAIT, argv[0], (const char* const*) argv);
#else
    execv(argv[0], (char* const*) argv);
    return 127;
#endif
}
")
add_executable(RunEditor   EXCLUDE_FROM_ALL "${CMAKE_CURRENT_BINARY_DIR}/launch/RunEditor.cpp")
add_executable(PackageGame EXCLUDE_FROM_ALL "${CMAKE_CURRENT_BINARY_DIR}/launch/PackageGame.cpp")
)cmake";
    return detail::Replace(tpl, "@NAME@", projectName);
}

// CMakePresets.json so opening the project folder in an IDE (CLion/VS/VSCode)
// configures against the local engine with no manual -D flags.
inline std::string CMakePresets(const std::string& engineBuildDir)
{
    const std::string tpl = R"json({
  "version": 3,
  "cmakeMinimumRequired": { "major": 3, "minor": 30, "patch": 0 },
  "configurePresets": [
    {
      "name": "default",
      "displayName": "Seraph (local engine)",
      "binaryDir": "${sourceDir}/cache/build",
      "cacheVariables": {
        "Seraph_DIR": "@ENGINE@",
        "CMAKE_BUILD_TYPE": "Debug"
      }
    }
  ]
}
)json";
    return detail::Replace(tpl, "@ENGINE@", engineBuildDir);
}

// A starter ScriptableEntity, ready to bind from the inspector.
inline std::string ExampleScriptHeader()
{
    return R"cpp(#pragma once

#include <Seraph/Scripts/ScriptableEntity.h>

// A starter script. Rename it, add gameplay in OnUpdate, then bind it to an
// entity from the inspector: Add Component > Script > ExampleScript.
class ExampleScript : public Seraph::ScriptableEntity
{
public:
    void OnCreate() override;
    void OnUpdate(f64 dt) override;
};
)cpp";
}

inline std::string ExampleScriptSource()
{
    return R"cpp(#include "ExampleScript.h"

#include <Seraph/Core/Log.h>
#include <Seraph/Scripts/ScriptRegistry.h>

void ExampleScript::OnCreate()
{
    SP_INFO_TAG("Scripting", "ExampleScript::OnCreate");
}

void ExampleScript::OnUpdate(f64 dt)
{
    (void)dt;
    // Your gameplay here. Read input with Seraph::Input::IsKeyDown(...),
    // move via Transform(), reach components with GetComponent<T>().
}

// Registers this class under the name a scene's ScriptComponent references.
SP_REGISTER_SCRIPT(ExampleScript, "ExampleScript")
)cpp";
}

inline std::string Readme(const std::string& projectName)
{
    return "# " + projectName + R"md(

A Seraph game project. Native C++ gameplay scripts live in `src/` and build into
a `Game` module (`cache/libGame`) that the editor/runtime load at runtime.

## Develop

Open this folder in your IDE (CLion / VS / VS Code). `CMakePresets.json` points
it at your local Seraph engine build, so it configures out of the box. Then:

- Build the **Game** target to compile your scripts.
- Run the **RunEditor** target (the green Run arrow) to open this project in the editor.
- Or open the editor yourself and use **Scripts > Compile Scripts** after edits.

## Package

Run the **PackageGame** target (or run `Seraph-Editor --package <this>.sproj`)
to produce a self-contained, runnable game folder.
)md";
}

} // namespace Seraph::ProjectTemplates
