//
// ScriptableEntity reflection root. Defines the base GetType(); the registration
// itself (SP_REFLECT_TYPE(...).Dynamic()) is GENERATED by SeraphHeaderTool from
// the SCLASS(dynamic) annotation on the class (see ScriptableEntity.h). Being a
// reflected, dynamic root is what lets SHT emit .Base<ScriptableEntity>() on
// subclasses and lets a base pointer resolve to its concrete Type via GetType().
// See Todo/plans/reflection-plan.md example B.
//

#include "Seraph/Scripts/ScriptableEntity.h"

#include "Seraph/Reflection/Reflection.h"

namespace Seraph
{

const Type& ScriptableEntity::GetType() const
{
    return Reflection::Get<ScriptableEntity>();
}

} // namespace Seraph
